# Generated by Django 5.1.6 on 2026-03-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_notification_user'),
        ('store', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='sub_total',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='saved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total amount saved', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
        ),
    ]
