# Generated by Django 5.1.6 on 2026-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_service_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='initiate_total',
            new_name='initial_total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
        ),
    ]
