# Generated by Django 5.1.6 on 2026-05-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_service',
            field=models.CharField(blank=True, choices=[('BlueDart', 'BlueDart'), ('DTDC', 'DTDC'), ('Delhivery', 'Delhivery'), ('India Post', 'India Post')], default=None, max_length=100, null=True),
        ),
    ]
