# Generated by Django 5.1.6 on 2026-06-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_orderitem_shipping_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
