# ====================================
# IMPORT STATEMENTS
# ====================================

# Importing Django's database models module
# models: Contains all the classes and tools needed to define database tables
# We use this to create our custom User and Profile models
from django.db import models

# Create your models here.
# This comment is auto-generated by Django - marks where you define your models

# Importing Django's built-in abstract user class
# AbstractUser: A pre-built User model with username, password, email, etc.
# We inherit from this instead of creating a user model from scratch
# It provides: username, first_name, last_name, email, password, is_staff, is_active, date_joined, etc.
from django.contrib.auth.models import AbstractUser

# Importing Django's timezone utilities
# timezone: Provides timezone-aware datetime objects
# Used for handling dates/times correctly across different timezones
from django.utils import timezone


# ====================================
# USER_TYPE CHOICES
# ====================================

# USER_TYPE: A tuple of tuples defining the choices for user types
# Used in the Profile model's user_Type field
# Format: (('database_value', 'human_readable_label'), ...)
# First value: What gets stored in the database ('Vendor', 'Customer')
# Second value: What displays in forms/admin (also 'Vendor', 'Customer')
# Note: Both are capitalized here, but in your forms.py you use lowercase
USER_TYPE = (
    ('Vendor', 'Vendor'),      # Vendor account type
    ('Customer', 'Customer'),  # Customer account type
)


# ====================================
# CUSTOM USER MODEL
# ====================================

# User: Custom user model that extends Django's AbstractUser
# Why custom? To use email as the login instead of username
# This model represents the 'users' table in your database
# Each User instance = one row in the database
class User(AbstractUser):
    # ====================================
    # FIELDS
    # ====================================
    
    # username: CharField for storing username
    # max_length=50: Maximum 50 characters allowed
    # unique=True: No two users can have the same username (enforced at database level)
    # null=True: Database can store NULL for this field (allows empty in DB)
    # blank=True: Forms can submit this field empty (allows empty in forms)
    # Why null and blank? Because we're using email as primary identifier, username is optional
    username = models.CharField(max_length=50, unique=True, null=True, blank=True)
    
    # email: EmailField for storing email addresses
    # max_length=255: Maximum 255 characters (standard for emails)
    # unique=True: No two users can have the same email (enforced at database level)
    # This will be used for login instead of username
    email = models.EmailField(max_length=255, unique=True)



# USERNAME_FIELD: Tells Django which field to use for authentication/login
# 'email': Users will log in with their email address instead of username
# This overrides the default 'username' from AbstractUser
#  
    USERNAME_FIELD = 'email'

# REQUIRED_FIELDS: List of fields prompted when creating a superuser with 'createsuperuser'
# ['username']: When creating a superuser, Django will ask for username (in addition to email and password)
# Note: USERNAME_FIELD and password are always required, so don't list them here
#   
    REQUIRED_FIELDS = ['username']


# ====================================
# USER MODEL METHODS
# ====================================

# __str__: String representation of the User object
# Called when you print(user) or display the object in Django admin
# self: Refers to the current User instance
# Returns: The user's email address as a string
# Example: If email is "john@example.com", this returns "john@example.com"
# 
    def __str__(self):
        # self.email: Gets the email field of this User instance
        # return: Sends this value back when __str__ is called
        return self.email

# save: Custom save method that runs every time a User is saved to the database
# *args: Accepts any positional arguments
# **kwargs: Accepts any keyword arguments
# This method overrides the default save() from AbstractUser
# Purpose: Automatically generate a username from email if username is not provided
#   
    def save(self, *args, **kwargs):
        # self.email.split('@'): Splits the email at the @ symbol
        # Example: "john@example.com".split('@') returns ['john', 'example.com']
        # email_username: Variable storing the part before @ (e.g., 'john')
        
        
        email_username = self.email.split('@')[0]
    
    # if not self.username: Checks if username is empty/None/blank
    # Only runs if the user didn't provide a username
        if not self.username:
            # self.username = email_username: Sets username to the email prefix
            # self.email: Accesses the email field of this User instance
            # .split('@')[0]: Gets the part before the @ symbol
            self.username = email_username
        
        # super(User, self).save(*args, **kwargs): Calls the parent class's save method
        # super(): Gets the parent class (AbstractUser)
        # .save(*args, **kwargs): Runs the original save logic from AbstractUser
        # This actually saves the User to the database
        # Must be called after your custom logic to persist changes
        super(User, self).save(*args, **kwargs)


# ====================================
# PROFILE MODEL
# ====================================

# Profile: A model for storing additional user information
# Why separate? Keeps authentication (User) separate from profile data
# This follows the "one-to-one" pattern: 1 User has 1 Profile
# Each Profile instance = one row in the 'profiles' table
class Profile(models.Model):
    # ====================================
    # PROFILE FIELDS
    # ====================================
    
    # user: OneToOneField linking this Profile to a User
    # OneToOneField: Each Profile belongs to exactly one User, and each User has max one Profile
    # User: The model this field links to (our custom User model)
    # on_delete=models.CASCADE: If the User is deleted, delete this Profile too
    # Example: If User(id=5) is deleted, Profile(user_id=5) is automatically deleted
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # image: ImageField for storing the user's profile picture
    # upload_to='images': Uploaded files will be saved in MEDIA_ROOT/images/
    # default='default-user.jpg': If no image is uploaded, use this default image
    # null=True: Database can store NULL (no image)
    # blank=True: Forms can submit this field empty
    # Example: User uploads avatar.png → saved as /media/images/avatar.png
    image = models.ImageField(upload_to='images', default='default-user.jpg', null=True, blank=True)
    
    # full_name: CharField for storing the user's full name
    # max_length=50: Maximum 50 characters
    # choices=None: No dropdown choices (free text input)
    # null=True: Database can store NULL
    # blank=True: Forms can submit empty
    # Note: choices=None is redundant (CharField has no choices by default)
    full_name = models.CharField(max_length=50, choices=None, null=True, blank=True)
    
    # mobile: CharField for storing phone number
    # max_length=10: Only 10 digits (suitable for Indian mobile numbers without country code)
    # null=True: Database can store NULL
    # blank=True: Forms can submit empty
    # Note: Consider max_length=15 for international numbers
    mobile = models.CharField(max_length=15, null=True, blank=True)
    
    # user_Type: CharField for storing whether user is Vendor or Customer
    # max_length=150: Maximum 150 characters (overly generous for 'Vendor'/'Customer')
    # choices=USER_TYPE: Restricts values to the USER_TYPE tuple defined above
    # Creates a dropdown in forms with 'Vendor' and 'Customer' options
    # null=True: Database can store NULL
    # blank=True: Forms can submit empty
    # default=None: Default value is None/NULL if not specified
    #    INCONSISTENCY: USER_TYPE uses 'Vendor'/'Customer' but your form uses 'vendor'/'customer'
    user_Type = models.CharField(max_length=150, choices=USER_TYPE, null=True, blank=True, default=None)


# ====================================
# PROFILE MODEL METHODS
# ====================================

# __str__: String representation of the Profile object
# Returns: The username of the associated User
# Example: If profile.user.username is "john_doe", this returns "john_doe"
#   
    def __str__(self):
        # self.user: Gets the related User object (via OneToOneField)
        # .username: Gets the username field from that User
        # return: Sends this string back when __str__ is called
        return self.user.username

# save: Custom save method for Profile
# Automatically sets full_name to username if full_name is not provided
# Purpose: Ensures profile always has a name to display
#   
    def save(self, *args, **kwargs):
        # if not self.full_name: Checks if full_name is empty/None/blank
        # Only runs if full_name wasn't provided
        if not self.full_name:
            # self.full_name = self.user.username: Sets full_name to the User's username
            # self.user: Accesses the related User object
            # .username: Gets that User's username
            # Example: If username is "john_doe", full_name becomes "john_doe"
            self.full_name = self.user.username
        
        # super(Profile, self).save(*args, **kwargs): Calls parent class's save method
        # super(): Gets the parent class (models.Model)
        # .save(*args, **kwargs): Runs the original save logic
        # This actually saves the Profile to the database
        super(Profile, self).save(*args, **kwargs)
    
    @property
    def first_name(self):
        return self.full_name.split()[0] if self.full_name else ""


# ====================================
# HOW THESE MODELS CONNECT
# ====================================

# DATABASE RELATIONSHIP:
# User (1) ←→ (1) Profile
# - One User has exactly one Profile
# - One Profile belongs to exactly one User
# - Connected via Profile.user (OneToOneField)

# EXAMPLE:
# user = User.objects.create(email="john@example.com")
# profile = Profile.objects.create(user=user, mobile="1234567890")
# 
# Accessing related objects:
# user.profile → Gets the Profile for this User
# profile.user → Gets the User for this Profile

# AUTHENTICATION FLOW:
# 1. User logs in with email (USERNAME_FIELD = 'email')
# 2. Django authenticates against User model
# 3. Access profile info via user.profile.full_name, user.profile.image, etc.

# DATA STORAGE:
# User model → 'users' table (or 'userauths_user')
# Profile model → 'userauths_profile' table
# Linked by Profile.user_id foreign key pointing to User.id